#!/bin/bash
#
# opt_select_ncurses - Shell utilities for ncurses-based selector
#
# Copyright (c) 2025, Shyju N
# Email: n.shyju@gmail.com
#
# Licensed under the BSD 3-Clause License.
# See the LICENSE file in the project root for full license information.
#

source colors.sh

echo
date

if [ $# -eq 0 ]; then
    echo "Error: Please provide at least one command-line argument."
    echo "Usage: $0 argument1 [argument2] [argument3]..."
    exit 1
fi

if [ $# -gt 1 ]; then
    echo "Warning: Multi files mode. Some commands may not work. be cautious"
fi

# check there are new files
for arg in "$@"
do
    if [ ! -e "$arg" ]; then
        echo "Warning: '$arg' does not exist. Continuing. be cautious"
    fi
done

actual_files="$@"

echo "$0: files=$actual_files"
echo

# Generate a random temp_filename
temp_filename=$(mktemp)

rm -rfv $temp_filename
echo "File: $actual_files. Select the operation: " > $temp_filename

echo "vi" >> $temp_filename
echo "git diff" >> $temp_filename
echo "git add -p" >> $temp_filename
echo "git commit -o" >> $temp_filename
echo "git add" >> $temp_filename
echo "git checkout" >> $temp_filename
echo "git difftool" >> $temp_filename
echo "git diff --staged" >> $temp_filename
echo "git commit" >> $temp_filename
echo "git restore --staged" >> $temp_filename
echo "git show HEAD" >> $temp_filename
echo "git log" >> $temp_filename
echo "gitk" >> $temp_filename
echo "cat" >> $temp_filename
echo "cat -n" >> $temp_filename
echo "rm -rfv" >> $temp_filename
echo "ls -lah" >> $temp_filename
echo "git blame" >> $temp_filename
echo "copy file content to clipboard" >> $temp_filename
echo "copy path to clipboard" >> $temp_filename
echo "copy full-path to clipboard" >> $temp_filename
echo "cd to file location" >> $temp_filename

opt_select_ncurses in_file=$temp_filename out_file=$temp_filename
return_value=$?
# check if opt_select_ncurses returned non-zero
if [ $return_value -ne 0 ]; then
    echo "opt_select_ncurses failed with exit code: $return_value"
    rm -rf $temp_filename
    exit
fi

operation=`cat $temp_filename`
echo selected operation=$operation
rm -rf $temp_filename

case $operation in
    "copy path to clipboard")
        echo $actual_files | xsel -i
        exit
        ;;
    "copy full-path to clipboard")
        echo `realpath $actual_files`
        echo `realpath $actual_files` | xsel -i
        exit
        ;;
    "copy file content to clipboard")
        cat $actual_files | xclip -selection c
        exit
        ;;
    "git diff --staged")
        git diff --staged
        exit
        ;;
    "git commit")
        git commit
        exit
        ;;
    "cd to file location")
        echo "cd to location"
        echo "cd $(dirname $actual_files)"
        echo "cd $(dirname $actual_files)/" > /home/snarangaprath/WORK/BASH_CMDS/cdloc
        echo " contents"
        cat /home/snarangaprath/WORK/BASH_CMDS/cdloc
        echo " contents"
        source /home/snarangaprath/WORK/BASH_CMDS/cdloc
        exit
        ;;
    "gitk")
        gitk $actual_files &
        exit
        ;;
    *)  # Default case (optional)
        cmd=`echo $operation $actual_files`
        ;;
esac

echo
echo "Running command: $cmd"
echo
echo "Press Enter to continue"
echo
read
$cmd

echo
echo
echo "=====================DONE=============="
echo
echo -e "${RED}Press Enter to redo. CTRL+C to exit${RESET}"
echo
echo -e "${CYAN}command: fops $actual_files ${RESET}"
echo
read
fops $actual_files
