#!/bin/bash
#
# opt_select_ncurses - Shell utilities for ncurses-based selector
#
# Copyright (c) 2025, Shyju N
# Email: n.shyju@gmail.com
#
# Licensed under the BSD 3-Clause License.
# See the LICENSE file in the project root for full license information.
#


count=`git status --short --untracked-files=no --untracked-files=normal | sed 's/^?/ /' | grep -v "^M.*" | wc -l`

if [ $count -eq 0 ] ; then
    echo "No file found in that name"
    echo
    exit
else
    # Generate a random temp_filename
    temp_filename=$(mktemp)
    echo "random file name: $temp_filename"
    echo
    rm -rf $temp_filename
    echo "Enter your choice : " > $temp_filename
    git status --short --untracked-files=no --untracked-files=normal | sed 's/^?/ /' | grep -v "^M.*" >> $temp_filename
    echo
    opt_select_ncurses in_file=$temp_filename out_file=$temp_filename multi_select=yes
    return_value=$?
    # check if opt_select_ncurses returned non-zero
    if [ $return_value -ne 0 ]; then
        echo "opt_select_ncurses failed with exit code: $return_value"
        rm -rf $temp_filename
        exit
    fi
    selected=`cat $temp_filename | sed 's/\,.../ /g' | sed 's/^...//'`
    rm -rf $temp_filename
fi

echo "$0: file: $selected"

fops $selected
